config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
Rails.application.routes.draw do
  get 'solver/index'
  post 'solver/letters'
  root 'solver#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/solver_controller.rb
class SolverController < ApplicationController

  # GET /
  # GET /solver/index
  def index; end

  # POST /solver/letters
  def letters
    letter1 = params[:letter1].downcase
    letter2 = params[:letter2].downcase
    letter3 = params[:letter3].downcase
    letter4 = params[:letter4].downcase
    letter5 = params[:letter5].downcase
    letter6 = params[:letter6].downcase
    unless letter1.empty? || letter2.empty? || letter3.empty? || letter4.empty? || letter5.empty? || letter6.empty?
      wl = WordList.new
      @words = wl.check_letters(letter1, letter2, letter3, letter4, letter5, letter6)
    else
      redirect_to root_path
      return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/solver_helper.rb
module SolverHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whirly Wordlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/solver/index.html.erb
<h1>Whirly Word Solver</h1>

<%= form_tag(solver_letters_path, method: 'post') do %>
  <%= label_tag(:letter1, "Letter 1:") %>
  <%= text_field_tag(:letter1, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= label_tag(:letter1, "Letter 2:") %>
  <%= text_field_tag(:letter2, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= label_tag(:letter1, "Letter 3:") %>
  <%= text_field_tag(:letter3, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= label_tag(:letter1, "Letter 4:") %>
  <%= text_field_tag(:letter4, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= label_tag(:letter1, "Letter 5:") %>
  <%= text_field_tag(:letter5, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= label_tag(:letter1, "Letter 6:") %>
  <%= text_field_tag(:letter6, nil, :maxlength => 1, :size => 2) %>
  <br />

  <%= submit_tag("See Some Words") %>
<% end %>

app/views/solver/letters.html.erb
<p>Here are some possibilities.  YMMV.</p>

<ul>
  <% @words.each do |word| %>
  <li><%= word %></li>
  <% end %>
</ul>

<%= link_to 'Solve another', root_path %>